# Unsupervised Machine Learning Final Project
Aug2023

Data Source: https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

# Project Goals
For this project we'll be looking at text messages and classifying them as spam or legitimate (ham) text messages. The data is labeled, and we'll start with using an unsupervised model and compare it against a supervised model. Stepwise, we'll be doing the following:
1. Import the data
2. Clean the data
3. Explore the data
4. Build the unsupervised model
5. Explore improvements to the unsupervised model
6. Build a supervised model
7. Explore improvements to the supervised model
8. Compare supervised vs. unsupervised models
9. Conclusions

# The Data
This data contains text messages collected from a various number of sources (also described in more detail on the Kaggle source url):
1. 425 spam messages from Grumbletext website
2. 3,375 ham messages from NUS SMS Corpus
3. 450 ham messages from Caroline Tag's PhD thesis
4. 1000 ham messages and 322 spam messages from SMS Spam Corpus v.0.1 Big

In total there are 5572 messages with a breakdown of 87% ham and 13% spam. 

## NOTE
The data doesn't use the default utf-8 encoding, we need to use ISO-8859-1 to read the raw data correctly.

In [1]:
# Import modules
import polars as pl
import altair as alt
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import enchant

from sklearn.cluster import AgglomerativeClustering as Agg
from sklearn.neighbors import KNeighborsClassifier as KNN

In [2]:
# Import the data
url = "https://raw.githubusercontent.com/nsxydis/final-project/main/spam.csv"
df = pl.read_csv(url, encoding = 'ISO-8859-1')

In [3]:
# Clean the data
df.to_pandas().info()

# Review '' column
print("\n'' column")
print(df[''].unique(), '\n')

print('_duplicated_0 column')
print(df['_duplicated_0'].unique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   v1             5572 non-null   object
 1   v2             5572 non-null   object
 2                  50 non-null     object
 3   _duplicated_0  12 non-null     object
dtypes: object(4)
memory usage: 174.3+ KB

'' column
shape: (44,)
Series: '' [str]
[
	" b'coz nobody …
	" we made you h…
	"JUST REALLYNEE…
	" justthought i…
	"JUST GOT PAYED…
	" but watever u…
	" Dont Come Nea…
	" the person is…
	" but dont try …
	".;-):-D""
	" but dont try …
	"\" not \"what …
	…
	" the toughest …
	"PROBPOP IN & C…
	" like you are …
	" HOWU DOIN? FO…
	" just as a sho…
	" But at d end …
	" HAD A COOL NY…
	" PO Box 1146 M…
	" ENJOYIN INDIA…
	" hopeSo hunny.…
	" Gud night....…
	" that's the ti…
	" smoke hella w…
] 

_duplicated_0 column
shape: (11,)
Series: '_duplicated_0' [str]
[
	" why to miss t…
	"whoever is the

# Data Cleaning
It appears some of the data was split into separate columns because there were commas in the text fields. We'll combine these columns together and clean up the data. Additionally we'll rename the columns and drop unnecessary fields.

NOTE: Upon further testing the additional text fields severely impact model performance and will be ignored. The columns are not noted in the source data page, so it is unclear what this data is.

In [4]:
def append(x):
    a = x['v2']
    
    # Get the blank column and add a comma if theres data
    b = x[''] 
    b = f", {b}" if b != '' else ""

    c = x['_duplicated_0']
    c = f", {c}" if c != '' else ""

    return a + b + c

struct = ['v2', '', '_duplicated_0']
df = df.with_columns(pl.struct(struct).apply(lambda x: append(x)).alias('text'))
df = df.rename({'v1' : 'category'})
df = df.drop(['v2', '', '_duplicated_0'])

In [5]:
# Rename the dataset and drop the extra columns
# df = df.rename({'v1' : 'category', 'v2' : 'text'})
# df = df.drop(['', '_duplicated_0'])

# Exploring the data

In [6]:
# Add the word count to the data
def wordCount(text):
    return len(text.split(' '))

df = df.with_columns(pl.col('text').apply(lambda x: wordCount(x)).alias('words'))

In [7]:
# Explore the data
alt.data_transformers.disable_max_rows()

# Spam vs Ham
title = ['Click the columns to separate the distributions', "Count of spam vs. ham messages"]
selection = alt.selection_point(encodings = ['x'])
breakdown = alt.Chart(df.to_pandas(), title = title).mark_bar().encode(
    x = 'category',
    y = 'count()',
    color = 'category'
).add_params(selection)

# Distribution of message length
title = "Distribution of word counts"
distribution = alt.Chart(df.to_pandas(), title = title).mark_bar().encode(
    x = alt.X('words', bin = True),
    y = 'count()',
    color = 'category'
).transform_filter(selection)

breakdown | distribution

alt.HConcatChart(...)

# Distribution notes
We can see that the normal (ham) messages are mostly under 20 words and skewed whereas the spam messages are typically between 20 to 40 words with a more normal (but still skewed) distribution.

# Model Fitting
Next we'll try fitting a NMF model based on the text field. To do that we'll have to vectorize the words and then fit our model.

In [8]:
# Make a class that can be used for different models
class spamhamNMF:
    def __init__(self, data, testSize = 0.3):
        # Vectorization
        self.vectorizer = TfidfVectorizer()
        self.embed = self.vectorizer.fit(df['text'].to_list())

        # Separate the data
        self.x = data['text'].to_list()
        self.y = data['category'].to_list()

        # Train test split
        self.x_train, self.x_test, self.y_train, self.y_test = \
        train_test_split(self.x, self.y, test_size = testSize, random_state=42)

        # Initialize the model
        self.model = NMF(n_components=2, random_state=42)

        ###############

    def train(self, report = True):
        '''Predict and score the training data'''
        self.embedTrain = self.vectorizer.transform(self.x_train)
        self.model.fit(self.embedTrain)
        matrix = self.model.transform(self.embedTrain)
        self.ypTrain = [np.argmax(row) for row in matrix]

        # Score
        self.trainScore, self.ypTrain = self.score(self.y_train, self.ypTrain)
        if report:
            print(f"Train Accuracy: {self.trainScore}")


    def test(self, report = True):
        '''Predict and score the test data'''
        self.embedTest = self.vectorizer.transform(self.x_test)
        matrix = self.model.transform(self.embedTest)
        self.ypTest = [np.argmax(row) for row in matrix]

        # Score
        self.testScore, self.ypTest = self.score(self.y_test, self.ypTest)
        if report:
            print(f"Test Accuracy: {self.testScore}")

    def score(self, y, yp):
        '''Categories yp and scores it against y'''
        # Determine which number aligns with each group
        df = pl.DataFrame({'y' : y, 'yp' : yp})
        ham = df.filter(pl.col('y') == 'ham')
        spam = df.filter(pl.col('y') == 'spam')

        ypHam = ham['yp'].mode()[0]
        ypSpam = spam['yp'].mode()[0]

        # Check that both groups weren't assigned together
        if ypHam == ypSpam:
            alternate = 1 if ypHam == 0 else 1
            
            if len(ham) > len(spam):
                ypSpam = alternate    
            else:
                ypHam = alternate

        # Create a dictionary
        if ypHam == 0:
            pred = {0 : 'ham', 1 : 'spam'}
        else:
            pred = {0 : 'spam', 1 : 'ham'}

        # Convert the predictions
        ypConverted = []
        for item in yp:
            ypConverted.append(pred[item])

        # Score the accuracy
        count = 0
        for n in range(len(y)):
            if y[n] == ypConverted[n]:
                count += 1

        # Return the accuracy and converted yp
        return count / len(y), ypConverted

In [9]:
nmf = spamhamNMF(df)
nmf.train()
nmf.test()
confusion_matrix(nmf.y_test, nmf.ypTest)

Train Accuracy: 0.5169230769230769
Test Accuracy: 0.5394736842105263


array([[872, 581],
       [189,  30]], dtype=int64)

# NMF Model improvements Part 1
Let's try removing stop words and seeing the impact.

In [10]:
def stopWords(text):
    '''Remove stopwords from the text'''
    stop = set(stopwords.words('english'))
    words = word_tokenize(text)
    new = ""
    for word in words:
        if word not in stop and (word.replace('-', "").isalnum()):
            new += f" {word}"
    return new

dfImproved = df.with_columns(pl.col('text').apply(lambda x: stopWords(x)))

In [11]:
nmf = spamhamNMF(dfImproved)
nmf.train()
nmf.test()
confusion_matrix(nmf.y_test, nmf.ypTest)

Train Accuracy: 0.8635897435897436
Test Accuracy: 0.8648325358851675


array([[1339,  114],
       [ 112,  107]], dtype=int64)

# NMF Model Improvements Part 1 Results

# NMF Model improvements Part 2
Let's try converting slang words to plain english.

In [12]:
dfSlang = {}
d = enchant.Dict('en_US')
def slang(text):
    '''Creates a list of slang words if there are any, otherwise returns []'''
    slangWords = []
    words = word_tokenize(text)
    for word in words:
        if d.check(word) == False:
            slangWords.append(word)
            if word.lower() not in dfSlang:
                dfSlang[word.lower()] = 1
            else:
                dfSlang[word.lower()] += 1
    return slangWords

dfImproved2 = dfImproved.with_columns(pl.col('text').apply(lambda x: slang(x)).alias('slang'))

In [13]:
# Identify the most used slang words
temp = {
    'word' : [],
    'count' : []
}
for word in dfSlang:
    temp['word'].append(word)
    temp['count'].append(dfSlang[word])

dfSlang = pl.DataFrame(temp)
del temp
dfSlang = dfSlang.sort(by = 'count', descending = True)
dfSlang = dfSlang.filter(pl.col('count') > 20)

In [14]:
# Manually adjusted slang translation
slangTranslation = {'lt': 'love that',
 'ur': 'your',
 'ok': 'okay',
 'txt': 'text',
 'lor': '?',
 'da': 'dad',
 'dont': "do not",
 'pls': 'please',
 'na': 'no',
 'im': 'I am',
 'msg': 'message',
 'lol': 'laughing out loud',
 'gon': 'gone',
 'gud': 'good',
 'ìï': '?',
 'haha': 'hah',
 'thk': 'thanks',
 'mins': 'minutes',
 'sms': 'message',
 'thats': 'that is',
 'liao': 'already',
 'luv': 'love',
 '150ppm': '150 parts per million',
 'aight': 'alright',
 'thanx': 'thanks',
 'leh': 'you',
 'didnt': 'did not',
 'tmr': 'tomorrow',
 'wif': 'wife',
 '150p': '150 parts per million',
 'hav': 'have',
 'abt': 'about',
 'juz': 'just',
 'tv': 'television',
 'plz': 'please',
 'havent': 'have not',
 'haf': 'have',
 'oso': 'significant other',
 'goin': 'going',
 'colour': 'color',
 'todays': "today's",
 'wid': 'with',
 'sae': '?'}

In [15]:
# Function to add slang words to our translator
def translate(slangWord):
    if word not in slangTranslation:
        slangTranslation[word] = input(f"{word}: ")

for word in dfSlang['word'].to_list():
    translate(word)


In [16]:
# Convert the slang words to normal words
def convertSlang(text):
    words = word_tokenize(text)
    new = ""
    for word in words:
        if word.lower() in slangTranslation:
            word = slangTranslation[word.lower()]
            if word == "?":
                word = ""
        new += f" {word}"
    return new

dfImproved2 = dfImproved2.with_columns(pl.col('text').apply(lambda x: convertSlang(x)))    

In [17]:
nmf = spamhamNMF(dfImproved2)
nmf.train()
nmf.test()
confusion_matrix(nmf.y_test, nmf.ypTest)

Train Accuracy: 0.8171794871794872
Test Accuracy: 0.8235645933014354


array([[1377,   76],
       [ 219,    0]], dtype=int64)

# Unsupervised Model Improvements Part 2 Results
From our second round we see that the performance has declined greatly from the previous models. That would suggest that the use of slang is quite important in separating spam from non spam messages. The model now heavily over classifies messages as spam and is very inaccurate.

In [18]:
class spamhamKNN:
    def __init__(self, data, neighbors = 3, testSize = 0.3):
        # Vectorization
        self.vectorizer = TfidfVectorizer()
        self.embed = self.vectorizer.fit(df['text'].to_list())

        # Separate the data
        self.x = data['text'].to_list()
        self.y = data['category'].to_list()

        # Train test split
        self.x_train, self.x_test, self.y_train, self.y_test = \
        train_test_split(self.x, self.y, test_size = testSize, random_state=42)

        # Initialize the model
        self.model = KNN(n_neighbors=neighbors)

    def train(self, report = True):
        '''Predict and score the training data'''
        self.embedTrain = self.vectorizer.transform(self.x_train)
        self.model.fit(self.embedTrain, self.y_train)
        self.ypTrain = self.model.predict(self.embedTrain)
        self.trainAccuracy = self.model.score(self.embedTrain, self.y_train)
        if report:
            print(f"Train Accuracy: {self.trainAccuracy}")
    
    def test(self, report = True):
        '''Predict and score the test data'''
        self.embedTest = self.vectorizer.transform(self.x_test)
        self.ypTest = self.model.predict(self.embedTest)
        self.testAccuracy = self.model.score(self.embedTest, self.y_test)
        if report:
            print(f"Test Accuracy: {self.testAccuracy}")


In [26]:
for n in range(1, 11, 2):
    print(f"{n} neighbors")
    knn = spamhamKNN(dfImproved2, neighbors=n)
    knn.train()
    knn.test()

1 neighbors
Train Accuracy: 1.0
Test Accuracy: 0.9754784688995215
3 neighbors
Train Accuracy: 0.9792307692307692
Test Accuracy: 0.9671052631578947
5 neighbors
Train Accuracy: 0.9705128205128205
Test Accuracy: 0.9617224880382775
7 neighbors
Train Accuracy: 0.9666666666666667
Test Accuracy: 0.9557416267942583
9 neighbors
Train Accuracy: 0.9635897435897436
Test Accuracy: 0.9533492822966507


In [20]:
knn = spamhamKNN(df, neighbors=3)
knn.train()
knn.test()
confusion_matrix(knn.y_test, knn.ypTest)

Train Accuracy: 0.9743589743589743
Test Accuracy: 0.9700956937799043


array([[1450,    3],
       [  47,  172]], dtype=int64)

In [24]:
knn = spamhamKNN(dfImproved, neighbors=3)
knn.train()
knn.test()
confusion_matrix(knn.y_test, knn.ypTest)

Train Accuracy: 0.977948717948718
Test Accuracy: 0.9641148325358851


array([[1451,    2],
       [  58,  161]], dtype=int64)

In [23]:
knn = spamhamKNN(dfImproved2, neighbors=3)
knn.train()
knn.test()
confusion_matrix(knn.y_test, knn.ypTest)

Train Accuracy: 0.9792307692307692
Test Accuracy: 0.9671052631578947


array([[1452,    1],
       [  54,  165]], dtype=int64)

In [21]:
class spamhamAgg:
    def __init__(self, data, testSize = 0.3):
        # Vectorization
        self.vectorizer = TfidfVectorizer()
        self.embed = self.vectorizer.fit(df['text'].to_list())

        # Separate the data
        self.x = data['text'].to_list()
        self.y = data['category'].to_list()

        # Train test split
        self.x_train, self.x_test, self.y_train, self.y_test = \
        train_test_split(self.x, self.y, test_size = testSize, random_state=42)

        # Initialize the model
        self.model = Agg(n_clusters=2)

    def train(self, report = True):
        '''Predict and score the training data'''
        self.embedTrain = self.vectorizer.transform(self.x_train)
        self.ypTrain = self.model.fit_predict(self.embedTrain.toarray())

        # Score
        self.trainScore, self.ypTrain = self.score(self.y_train, self.ypTrain)
        if report:
            print(f"Train Accuracy: {self.trainScore}")

    def test(self, report = True):
        '''Predict and score the test data'''
        self.embedTest = self.vectorizer.transform(self.x_test)
        self.ypTest = self.model.fit_predict(self.embedTest.toarray())

        # Score
        self.testScore, self.ypTest = self.score(self.y_test, self.ypTest)
        if report:
            print(f"Test Accuracy: {self.testScore}")

    def score(self, y, yp):
        '''Categories yp and scores it against y'''
        # Determine which cluster aligns with each group
        df = pl.DataFrame({'y' : y, 'yp' : yp})
        ham = df.filter(pl.col('y') == 'ham')
        spam = df.filter(pl.col('y') == 'spam')

        ypHam = ham['yp'].mode()[0]
        ypSpam = spam['yp'].mode()[0]

        # Check that both groups weren't assigned together
        if ypHam == ypSpam:
            alternate = 1 if ypHam == 0 else 1
            
            if len(ham) > len(spam):
                ypSpam = alternate    
            else:
                ypHam = alternate

        # Create a dictionary
        if ypHam == 0:
            pred = {0 : 'ham', 1 : 'spam'}
        else:
            pred = {0 : 'spam', 1 : 'ham'}

        # Convert the predictions
        ypConverted = []
        for item in yp:
            ypConverted.append(pred[item])

        # Score the accuracy
        count = 0
        for n in range(len(y)):
            if y[n] == ypConverted[n]:
                count += 1

        # Return the accuracy and converted yp
        return count / len(y), ypConverted

In [22]:
agg = spamhamAgg(df)
agg.train()
agg.test()
confusion_matrix(agg.y_test, agg.ypTest)

agg = spamhamAgg(dfImproved)
agg.train()
agg.test()
confusion_matrix(agg.y_test, agg.ypTest)

agg = spamhamAgg(dfImproved2)
agg.train()
agg.test()
confusion_matrix(agg.y_test, agg.ypTest)

Train Accuracy: 0.8594871794871795
Test Accuracy: 0.8588516746411483
Train Accuracy: 0.8592307692307692
Test Accuracy: 0.8594497607655502
Train Accuracy: 0.8446153846153847
Test Accuracy: 0.8438995215311005


array([[1411,   42],
       [ 219,    0]], dtype=int64)